version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Zipping the lambda function and AppSpec file"
      - zip -r lambda-function.zip index.mjs appspec.yml
  post_build:
    commands:
      - echo "deploying the lambda"
      - aws lambda update-function-code --function-name e-commerce-api-lambda --zip-file fileb://lambda-function.zip
# needed for code deploy
# artifacts:
#   files:
#     - function.zip
#     - appspec.yml 