version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo 'Installing'
  pre_build:
    commands:
      - echo 'Installing source NPM dependencies.'
      - npm install
  build:
    commands:
      - echo "Zipping the lambda function and AppSpec file"
      - zip -r lambda-function.zip . -x buildspec.yaml
      - npm run lint
      - npm test
  post_build:
    commands:
      - echo "deploying the lambda"
      - aws lambda update-function-code --function-name e-commerce-api-lambda --zip-file fileb://lambda-function.zip