version: 0.2

phases:
  install:
  commands:
    - echo "Installing dependencies"
  build:
    commands:
      - echo "Zipping the lambda function and AppSpec file"
      - zip -f function.zip function appspec.yml
artifacts:
  files:
    - function.zip
    - appspec.yml