version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Zipping the lambda function and AppSpec file"
      - zip -r function.zip index.js appspec.yml
artifacts:
  files:
    - function.zip
    - appspec.yml